# Docker Compose simple para usuarios finales
# Usa la imagen pre-construida desde GitHub Container Registry
version: '3.8'

services:
  docling-service:
    image: ghcr.io/dmayab/docling-service:latest
    container_name: docling-service
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - ENVIRONMENT=production
    volumes:
      # Directorio temporal para archivos procesados
      - ./temp:/app/temp
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  temp-storage:
    driver: local